### PR TITLE
fix: will show import error message + allow to rerun if any worker err occurs

### LINKED ISSUE #156: Error doesn't show when there's a failed module import
Image

/bounty $10

May be connected to https://github.com/tscircuit/eval-webworker

### PR DESCRIPTION
**Pull request by ArnavK-09**
/claim #156

fix #156

image

### CODE REVIEW

File: lib/components/RunFrame.tsx [hunk 1]
```diff
@@ -232,13 +232,15 @@ export const RunFrame = (props: Props) => {
         .then(() => ({ success: true }))
         .catch((e: any) => {
           // removing the prefix "Eval compiled js error for "./main.tsx":"
-          const message = e.message.split(":")[1]
+          const message: string = e.message.includes(":")
+            ? e.message.split(":")[1]
```
Comment (seveibar) [inline lib/components/RunFrame.tsx:236]: What if the error message has multiple colons?

```suggestion
            ? e.message.replace(/[^:]+:/, "")
```

**Review by seveibar — APPROVED** [review]
very nice work
