### PR TITLE
fix: Better error msg and handling of infinitely loading runframe

### LINKED ISSUE #249: RunFrame errors sometimes cause it to run infinitely, give a better error if user doesn't specify any code to run
Image

/bounty $10

### PR DESCRIPTION
**Pull request by Ayushjhawar8**
/claim #249
close #249

### CODE REVIEW

**Comment by Ayushjhawar8** [comment]
\ draft

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]

File: lib/components/RunFrame.tsx [hunk 1]
```diff
@@ -178,9 +178,10 @@ export const RunFrame = (props: Props) => {
 
       if (!fsMapObj[props.entrypoint]) {
         setError({
-          error: `Entrypoint not found (entrypoint: "${props.entrypoint}", fsMapKeys: ${Object.keys(fsMapObj).join(", ")})`,
+          error: `No code found at entry point "${props.entrypoint}". Make sure you've provided the correct entry file.`,
```
Comment (seveibar) [inline lib/components/RunFrame.tsx:181]: you need to handle if there are no files defined. Undo changes to the error message. Generally i will almost never create an issue to change an error message- it's never what i mean. If i wanted to change text i could do it faster than i could create the issue

**Review by seveibar — CHANGES_REQUESTED** [review]
did not handle case where there are no files provided or no entrypoint provided (which is what the issue calls for, and is a new case)

File: lib/components/RunFrame.tsx (hunk 1 above)
Comment (Ayushjhawar8) [reply lib/components/RunFrame.tsx]: okay got your point

**Review by seveibar — CHANGES_REQUESTED** [review]
your code is fantastic but we are strictly anti-mock

**Comment by seveibar** [comment]
@Ayushjhawar8 i think you could create examples (possibly in an error section) that emulate each error

**Comment by seveibar** [comment]
@Ayushjhawar8 in case the above comment was unclear, i meant cosmos examples!!!

**Comment by Ayushjhawar8** [comment]
@seveibar i added example10-error-cases

File: lib/components/RunFrame/RunFrame.tsx [hunk 2]
```diff
@@ -174,7 +210,10 @@ export const RunFrame = (props: RunFrameProps) => {
           console.error(e)
           return { success: false }
         })
-      if (!evalResult.success) return setIsRunning(false)
+      if (!evalResult.success) {
+        setIsRunning(false)
+        return
+      }
```
Comment (seveibar) [inline lib/components/RunFrame/RunFrame.tsx:216]: @ArnavK-09 included this is his PR fwiw

File: examples/example10-error-cases.fixture.tsx [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+            fontFamily: "monospace",
+            height: "200px",
+            marginBottom: "1rem",
+          }}
+        />
+        <RunFrame fsMap={fsMap} entrypoint={entrypoint} showRunButton={true} />
+      </div>
+    </div>
+  )
+}
```
Comment (seveibar) [inline examples/example10-error-cases.fixture.tsx:79]: really good example here

File: lib/components/RunFrame/RunFrame.tsx (hunk 2 above)
Comment (ArnavK-09) [reply lib/components/RunFrame/RunFrame.tsx:216]: ?? did i

**Review by seveibar — APPROVED** [review]
